const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = 'https://sngmpumzlhomtvfvlbdn.supabase.co';
const supabaseKey = 'sb_publishable_d87ooNXCoOx2gqv9vAfGhQ_zPQJuFsb';
const supabase = createClient(supabaseUrl, supabaseKey);

const categories = [
  { category_id: 'Living Room', name: 'Phòng khách', slug: 'phong-khach', icon: 'Sofa', description: 'Nội thất phòng khách sang trọng' },
  { category_id: 'Kitchen', name: 'Nhà bếp', slug: 'nha-bep', icon: 'Utensils', description: 'Nội thất phòng ăn và bếp' },
  { category_id: 'Bedroom', name: 'Phòng ngủ', slug: 'phong-ngu', icon: 'Bed', description: 'Nội thất phòng ngủ êm ái' },
  { category_id: 'Curtains', name: 'Rèm cửa', slug: 'rem-cua', icon: 'Sliders', description: 'Rèm cửa cản sáng cao cấp' },
  { category_id: 'Storage', name: 'Lưu trữ', slug: 'luu-tru', icon: 'Box', description: 'Tủ kệ lưu trữ thông minh' },
  { category_id: 'Lavabo', name: 'Tủ lavabo', slug: 'tu-lavabo', icon: 'Droplets', description: 'Tủ lavabo phòng tắm cao cấp' }
];

const rawProducts = [
  { id: 19, product_id: 'P0019', name: 'Bàn Trà Gỗ Tròn Đôi Modern', category: 'Living Room', category_name: 'Phòng khách', price: 1850000, old_price: 2200000, stock: 25, status: 'In stock', badge: 'Hot', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/ban-2.jpg', description: 'Bàn trà tròn đôi mặt gỗ sồi chân sắt sơn tĩnh điện phong cách hiện đại cho phòng khách.', full_desc: 'Bàn Trà Gỗ Tròn Đôi Modern là giải pháp tuyệt vời cho phòng khách căn hộ chung cư hay nhà phố.', specs: { 'Chất liệu': 'Mặt gỗ MDF phủ Melamine, Chân sắt', 'Kích thước': 'Bàn lớn D70xH45cm, Bàn nhỏ D50xH40cm' } },
  { id: 20, product_id: 'P0020', name: 'Bàn Làm Việc Gỗ Khung Sắt Tối Giản', category: 'Living Room', category_name: 'Phòng khách', price: 2450000, old_price: 2900000, stock: 30, status: 'In stock', badge: 'Mới', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/ban-3.jpg', description: 'Bàn làm việc khung sắt chắc chắn, thiết kế tối giản hỗ trợ góc làm việc.', full_desc: 'Bàn Làm Việc Gỗ Khung Sắt Tối Giản được gia công từ khung thép hộp chắc chắn.', specs: { 'Chất liệu': 'Gỗ công nghiệp chống ẩm', 'Kích thước': '120 x 60 x 75 cm' } },
  { id: 21, product_id: 'P0021', name: 'Bàn Sofa Mặt Đá Vân Mây Sang Trọng', category: 'Living Room', category_name: 'Phòng khách', price: 3600000, old_price: 4100000, stock: 15, status: 'In stock', badge: '-12%', badge_type: 'badge-sale', image: 'assets/images/products/do-noi-that/ban-4.jpg', description: 'Bàn sofa mặt đá ceramic vân mây bóng bẩy.', full_desc: 'Bàn Sofa Mặt Đá Vân Mây Sang Trọng mang lại khí chất hiện đại.', specs: { 'Chất liệu': 'Mặt đá Ceramic vân mây', 'Kích thước': '130 x 70 x 45 cm' } },
  { id: 22, product_id: 'P0022', name: 'Bàn Trà Gỗ Nguyên Khối Rustic', category: 'Living Room', category_name: 'Phòng khách', price: 2100000, old_price: 2500000, stock: 18, status: 'In stock', badge: null, badge_type: null, image: 'assets/images/products/do-noi-that/ban-5.jpg', description: 'Bàn trà phong cách mộc mạc Rustic.', full_desc: 'Bàn Trà Gỗ Nguyên Khối Rustic tôn vinh nét đẹp chân thực.', specs: { 'Chất liệu': 'Gỗ me tây tự nhiên', 'Kích thước': '100 x 50 x 40 cm' } },

  { id: 23, product_id: 'P0023', name: 'Ghế Thư Giãn Bọc Nỉ Bông Nordic', category: 'Living Room', category_name: 'Phòng khách', price: 1450000, old_price: 1800000, stock: 40, status: 'In stock', badge: 'Mới', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/ghe-1.jpg', description: 'Ghế đệm nỉ bông êm ái thích hợp đọc sách.', full_desc: 'Ghế Thư Giãn Bọc Nỉ Bông Nordic tựa lưng ôm sát sống lưng.', specs: { 'Chất liệu': 'Nỉ bông cao cấp', 'Kích thước': '75 x 70 x 85 cm' } },
  { id: 24, product_id: 'P0024', name: 'Ghế Ăn Gỗ Tự Nhiên Bọc Da Eames', category: 'Kitchen', category_name: 'Nhà bếp', price: 890000, old_price: 1100000, stock: 50, status: 'In stock', badge: null, badge_type: null, image: 'assets/images/products/do-noi-that/ghe-2.jpg', description: 'Ghế ăn khung gỗ tự nhiên bọc đệm da PU.', full_desc: 'Ghế Ăn Gỗ Tự Nhiên Bọc Da Eames sở hữu kiểu dáng hiện đại.', specs: { 'Chất liệu': 'Khung gỗ cao su, đệm da PU', 'Kích thước': '45 x 48 x 82 cm' } },
  { id: 25, product_id: 'P0025', name: 'Ghế Sofa Đơn Thư Giãn Cao Cấp', category: 'Living Room', category_name: 'Phòng khách', price: 2290000, old_price: 2700000, stock: 20, status: 'In stock', badge: '-15%', badge_type: 'badge-sale', image: 'assets/images/products/do-noi-that/ghe-3.jpg', description: 'Ghế sofa đơn thiết kế bọc nệm dày dặn.', full_desc: 'Ghế Sofa Đơn Thư Giãn Cao Cấp là mảnh ghép điểm nhấn hoàn hảo.', specs: { 'Chất liệu': 'Vải nỉ nhung', 'Kích thước': '85 x 80 x 78 cm' } },
  { id: 26, product_id: 'P0026', name: 'Ghế Đôn Tròn Bọc Vải Nhung Tinh Tế', category: 'Living Room', category_name: 'Phòng khách', price: 490000, old_price: 650000, stock: 35, status: 'In stock', badge: null, badge_type: null, image: 'assets/images/products/do-noi-that/ghe-4.jpg', description: 'Ghế đôn nhỏ gọn bọc nhung mịn màng.', full_desc: 'Ghế Đôn Tròn Bọc Vải Nhung Tinh Tế có đường viền mạ vàng.', specs: { 'Chất liệu': 'Vải nhung tinh tế', 'Kích thước': 'D35 x H42 cm' } },
  { id: 27, product_id: 'P0027', name: 'Ghế Thư Giãn Khung Gỗ Cong Scandinavian', category: 'Living Room', category_name: 'Phòng khách', price: 1950000, old_price: 2300000, stock: 15, status: 'In stock', badge: 'Hot', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/ghe-5.jpg', description: 'Ghế bành uốn cong nghệ thuật Scandinavian.', full_desc: 'Ghế Thư Giãn Khung Gỗ Cong Scandinavian uốn gỗ hơi nước.', specs: { 'Chất liệu': 'Gỗ uốn cong nghệ thuật', 'Kích thước': '68 x 80 x 92 cm' } },

  { id: 28, product_id: 'P0028', name: 'Giường Bọc Nệm Phong Cách Châu Âu', category: 'Bedroom', category_name: 'Phòng ngủ', price: 6890000, old_price: 7500000, stock: 12, status: 'In stock', badge: 'Mới', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/giuong-1.jpg', description: 'Giường ngủ bọc nỉ cao cấp rút trán quả trám.', full_desc: 'Giường Bọc Nệm Phong Cách Châu Âu mang lại nét quý phái.', specs: { 'Chất liệu': 'Khung gỗ tự nhiên, Nệm nỉ', 'Kích thước': '180 x 200 cm' } },
  { id: 29, product_id: 'P0029', name: 'Giường Gỗ Tự Nhiên Tích Hợp Ngăn Kéo', category: 'Bedroom', category_name: 'Phòng ngủ', price: 5990000, old_price: 6600000, stock: 10, status: 'In stock', badge: null, badge_type: null, image: 'assets/images/products/do-noi-that/giuong-2.jpg', description: 'Giường ngủ tích hợp 2 ngăn kéo bên hông.', full_desc: 'Giường Gỗ Tự Nhiên Tích Hợp Ngăn Kéo thông minh.', specs: { 'Chất liệu': 'Gỗ sồi tự nhiên', 'Kích thước': '160 x 200 cm' } },
  { id: 30, product_id: 'P0030', name: 'Giường Ngủ Tối Giản Khung Gỗ Tần Bì', category: 'Bedroom', category_name: 'Phòng ngủ', price: 4590000, old_price: 5100000, stock: 18, status: 'In stock', badge: '-10%', badge_type: 'badge-sale', image: 'assets/images/products/do-noi-that/giuong-3.jpg', description: 'Giường gỗ Tần bì thanh lịch bo viền tròn.', full_desc: 'Giường Ngủ Tối Giản Khung Gỗ Tần Bì vân gỗ uốn lượn.', specs: { 'Chất liệu': 'Gỗ Tần bì nhập khẩu', 'Kích thước': '160 x 200 cm' } },
  { id: 31, product_id: 'P0031', name: 'Giường Ngủ Bọc Vải Nỉ Đầu Giường Mềm Mại', category: 'Bedroom', category_name: 'Phòng ngủ', price: 5490000, old_price: 6200000, stock: 14, status: 'In stock', badge: null, badge_type: null, image: 'assets/images/products/do-noi-that/giuong-4.jpg', description: 'Giường đầu tựa bọc đệm êm ái nâng đỡ tư thế.', full_desc: 'Giường Ngủ Bọc Vải Nỉ Đầu Giường Mềm Mại chân chắc chắn.', specs: { 'Chất liệu': 'Đầu giường bọc nỉ', 'Kích thước': '180 x 200 cm' } },
  { id: 32, product_id: 'P0032', name: 'Giường Ngủ Hiện Đại Khung Gỗ Sồi Nga', category: 'Bedroom', category_name: 'Phòng ngủ', price: 6200000, old_price: 7000000, stock: 8, status: 'In stock', badge: 'Hot', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/giuong-5.jpg', description: 'Giường ngủ bằng gỗ sồi Nga nguyên khối.', full_desc: 'Giường Ngủ Hiện Đại Khung Gỗ Sồi Nga đã qua xử lý sấy.', specs: { 'Chất liệu': 'Gỗ sồi Nga 100%', 'Kích thước': '180 x 200 cm' } },

  { id: 33, product_id: 'P0033', name: 'Rèm Cửa 2 Lớp Chống Nắng Cao Cấp', category: 'Curtains', category_name: 'Rèm cửa', price: 850000, old_price: 1050000, stock: 45, status: 'In stock', badge: 'Mới', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/rem-1.jpg', description: 'Rèm 2 lớp kết hợp vải dệt cản sáng 100%.', full_desc: 'Rèm Cửa 2 Lớp Chống Nắng Cao Cấp cản tia UV.', specs: { 'Chất liệu': 'Vải gấm nỉ + Voan lụa', 'Kích thước': '2.5m x 2.7m' } },
  { id: 34, product_id: 'P0034', name: 'Rèm Vải Voan Trắng Xuyên Sáng Tinh Khôi', category: 'Curtains', category_name: 'Rèm cửa', price: 520000, old_price: 680000, stock: 50, status: 'In stock', badge: null, badge_type: null, image: 'assets/images/products/do-noi-that/rem-2.jpg', description: 'Rèm voan trắng thêu hoa văn dịu dàng.', full_desc: 'Rèm Vải Voan Trắng Xuyên Sáng Tinh Khôi bồng bềnh lãng mạn.', specs: { 'Chất liệu': 'Voan lụa mỏng', 'Kích thước': '2.0m x 2.6m' } },
  { id: 35, product_id: 'P0035', name: 'Rèm Cầu Vồng Hàn Quốc Cản Sáng 95%', category: 'Curtains', category_name: 'Rèm cửa', price: 990000, old_price: 1200000, stock: 30, status: 'In stock', badge: '-18%', badge_type: 'badge-sale', image: 'assets/images/products/do-noi-that/rem-3.jpg', description: 'Rèm cuốn cầu vồng thông minh linh hoạt.', full_desc: 'Rèm Cầu Vồng Hàn Quốc Cản Sáng 95% có dây kéo mượt.', specs: { 'Chất liệu': 'Polyester 100%', 'Kích thước': '1.5m x 2.0m' } },
  { id: 36, product_id: 'P0036', name: 'Rèm Roman Xếp Lớp Phong Cách Hiện Đại', category: 'Curtains', category_name: 'Rèm cửa', price: 760000, old_price: 900000, stock: 35, status: 'In stock', badge: null, badge_type: null, image: 'assets/images/products/do-noi-that/rem-4.jpg', description: 'Rèm Roman xếp tầng vuông vắn gọn gàng.', full_desc: 'Rèm Roman Xếp Lớp Phong Cách Hiện Đại.', specs: { 'Chất liệu': 'Vải bố dệt', 'Kích thước': '1.2m x 1.8m' } },
  { id: 37, product_id: 'P0037', name: 'Rèm Vải Nỉ Dày Cách Nhiệt Chống Nắng', category: 'Curtains', category_name: 'Rèm cửa', price: 1150000, old_price: 1400000, stock: 25, status: 'In stock', badge: 'Hot', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/rem-5.jpg', description: 'Rèm nỉ dày cản nhiệt máy lạnh.', full_desc: 'Rèm Vải Nỉ Dày Cách Nhiệt Chống Nắng hạn chế âm thanh.', specs: { 'Chất liệu': 'Vải nỉ 3 lớp', 'Kích thước': '3.0m x 2.7m' } },

  { id: 38, product_id: 'P0038', name: 'Tủ Kệ Tivi Gỗ Hiện Đại 3 Ngăn Kéo', category: 'Storage', category_name: 'Lưu trữ', price: 2890000, old_price: 3300000, stock: 16, status: 'In stock', badge: 'Mới', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/tu-ke-1.jpg', description: 'Tủ kệ Tivi gỗ MDF chống ẩm phối màu sồi.', full_desc: 'Tủ Kệ Tivi Gỗ Hiện Đại 3 Ngăn Kéo rộng rãi.', specs: { 'Chất liệu': 'Gỗ MDF lõi xanh', 'Kích thước': '160 x 40 x 45 cm' } },
  { id: 39, product_id: 'P0039', name: 'Kệ Sách Gỗ Nhiều Tầng Tối Giản', category: 'Storage', category_name: 'Lưu trữ', price: 1350000, old_price: 1650000, stock: 28, status: 'In stock', badge: null, badge_type: null, image: 'assets/images/products/do-noi-that/tu-ke-2.jpg', description: 'Kệ sách 5 tầng bằng gỗ tự nhiên nhỏ gọn.', full_desc: 'Kệ Sách Gỗ Nhiều Tầng Tối Giản chắc chắn.', specs: { 'Chất liệu': 'Gỗ cao su 100%', 'Kích thước': '60 x 30 x 150 cm' } },
  { id: 40, product_id: 'P0040', name: 'Tủ Giày Thông Minh Cánh Lật Tiết Kiệm Diện Tích', category: 'Storage', category_name: 'Lưu trữ', price: 1790000, old_price: 2100000, stock: 22, status: 'In stock', badge: '-14%', badge_type: 'badge-sale', image: 'assets/images/products/do-noi-that/tu-ke-3.jpg', description: 'Tủ giày cánh lật 3 tầng chứa 25 đôi giày.', full_desc: 'Tủ Giày Thông Minh Cánh Lật Tiết Kiệm Diện Tích.', specs: { 'Chất liệu': 'Gỗ Melamine', 'Kích thước': '80 x 24 x 115 cm' } },
  { id: 41, product_id: 'P0041', name: 'Kệ Trang Trí Khung Sắt Mặt Gỗ Hiện Đại', category: 'Storage', category_name: 'Lưu trữ', price: 1150000, old_price: 1400000, stock: 30, status: 'In stock', badge: null, badge_type: null, image: 'assets/images/products/do-noi-that/tu-ke-4.jpg', description: 'Kệ đứng trang trí phong cách Industrial.', full_desc: 'Kệ Trang Trí Khung Sắt Mặt Gỗ Hiện Đại.', specs: { 'Chất liệu': 'Khung sắt, mặt gỗ', 'Kích thước': '80 x 35 x 140 cm' } },
  { id: 42, product_id: 'P0042', name: 'Tủ Quần Áo Gỗ Sồi 2 Cánh Mở Sang Trọng', category: 'Storage', category_name: 'Lưu trữ', price: 4850000, old_price: 5500000, stock: 10, status: 'In stock', badge: 'Hot', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/tu-ke-5.jpg', description: 'Tủ áo gỗ sồi tự nhiên 2 cánh lớn.', full_desc: 'Tủ Quần Áo Gỗ Sồi 2 Cánh Mở Sang Trọng.', specs: { 'Chất liệu': 'Gỗ sồi nguyên khối', 'Kích thước': '120 x 58 x 200 cm' } },

  { id: 43, product_id: 'P0043', name: 'Tủ Lavabo Phòng Tắm Gỗ Chống Nước', category: 'Lavabo', category_name: 'Tủ lavabo', price: 3250000, old_price: 3800000, stock: 18, status: 'In stock', badge: 'Mới', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/tu-lavabo-1.jpg', description: 'Tủ chậu rửa lavabo chất liệu PVC chống nước.', full_desc: 'Tủ Lavabo Phòng Tắm Gỗ Chống Nước kèm chậu sứ Nano.', specs: { 'Chất liệu': 'Nhựa PVC, Chậu sứ nano', 'Kích thước': '70 x 48 x 50 cm' } },
  { id: 44, product_id: 'P0044', name: 'Bộ Tủ Lavabo Treo Tường Kèm Gương Đèn LED', category: 'Lavabo', category_name: 'Tủ lavabo', price: 4190000, old_price: 4900000, stock: 14, status: 'In stock', badge: '-14%', badge_type: 'badge-sale', image: 'assets/images/products/do-noi-that/tu-lavabo-2.jpg', description: 'Bộ tủ chậu treo tường kèm gương đèn LED.', full_desc: 'Bộ Tủ Lavabo Treo Tường Kèm Gương Đèn LED tiện nghi.', specs: { 'Chất liệu': 'Nhựa PVC, gương Bỉ LED', 'Kích thước': '80 x 50 x 52 cm' } },
  { id: 45, product_id: 'P0045', name: 'Tủ Lavabo Nhôm Nôi Tấm Chống Ẩm Mốc', category: 'Lavabo', category_name: 'Tủ lavabo', price: 2990000, old_price: 3500000, stock: 20, status: 'In stock', badge: null, badge_type: null, image: 'assets/images/products/do-noi-that/tu-lavabo-3.jpg', description: 'Tủ lavabo hợp kim nhôm siêu nhẹ.', full_desc: 'Tủ Lavabo Nhôm Nôi Tấm Chống Ẩm Mốc.', specs: { 'Chất liệu': 'Hợp kim nhôm tấm', 'Kích thước': '60 x 47 x 48 cm' } },
  { id: 46, product_id: 'P0046', name: 'Bộ Tủ Lavabo Tân Cổ Điển Sang Trọng', category: 'Lavabo', category_name: 'Tủ lavabo', price: 5350000, old_price: 6100000, stock: 9, status: 'In stock', badge: 'Hot', badge_type: 'badge-new', image: 'assets/images/products/do-noi-that/tu-lavabo-4.jpg', description: 'Tủ chậu rửa hoa văn tân cổ điển.', full_desc: 'Bộ Tủ Lavabo Tân Cổ Điển Sang Trọng.', specs: { 'Chất liệu': 'Gỗ tràm chống ẩm', 'Kích thước': '90 x 52 x 82 cm' } },
  { id: 47, product_id: 'P0047', name: 'Tủ Lavabo Đôi Đổi Màu Cao Cấp', category: 'Lavabo', category_name: 'Tủ lavabo', price: 5990000, old_price: 6800000, stock: 7, status: 'In stock', badge: null, badge_type: null, image: 'assets/images/products/do-noi-that/tu-lavabo-5.jpg', description: 'Tủ lavabo 2 chậu rửa sinh hoạt tiện lợi.', full_desc: 'Tủ Lavabo Đôi Đổi Màu Cao Cấp mặt đá chống thấm.', specs: { 'Chất liệu': 'Khung PVC, Mặt đá 2 chậu', 'Kích thước': '120 x 50 x 50 cm' } }
];

async function run() {
  console.log('Ensuring all categories exist...');
  for (const c of categories) {
    const { error } = await supabase.from('categories').upsert(c, { onConflict: 'category_id' });
    if (error) console.warn(`Category ${c.category_id} error:`, error.message);
  }

  console.log('Upserting clean 29 furniture products to Supabase...');
  for (const p of rawProducts) {
    const { error } = await supabase.from('products').upsert(p, { onConflict: 'id' });
    if (error) {
      console.warn(`Product ${p.id} error:`, error.message);
    } else {
      console.log(`Product ${p.id} (${p.name}) upserted cleanly.`);
    }
  }
}

run();
